version: '3.8'
services:
    db:
        image: timescale/timescaledb:2.0.0-pg12
        restart: unless-stopped
        environment:
            POSTGRES_USER: $DB_USER
            POSTGRES_DB: $DATABASE_NAME
            POSTGRES_PASSWORD: $DB_PASS
        networks:
            - db-network
        volumes:
            - ./config/db/:/docker-entrypoint-initdb.d/
            - ./data/postgres:/var/lib/postgresql/data
    redis:
        image: redis
        restart: always
        volumes:
            - ./data/redis:/data
        networks:
            - queue-network
    superset:
        image: amancevice/superset
        restart: always
        depends_on:
            - redis
            - db
        networks:
            - queue-network
            - db-network
        volumes:
            - ./config/superset/config.py:/etc/superset/superset_config.py

networks:
    db-network:
    queue-network:
